definitions:
  dto.ExecuteRequest:
    properties:
      piston_execute_request:
        $ref: '#/definitions/dto.PistonExecuteRequest'
      task_id:
        type: string
    required:
    - piston_execute_request
    - task_id
    type: object
  dto.File:
    properties:
      content:
        type: string
      encoding:
        default: utf8
        type: string
      name:
        type: string
    required:
    - content
    type: object
  dto.MultiExecuteResponse:
    description: Response containing the results of test execution and linting issues.
    properties:
      language:
        description: The programming language used
        type: string
      lint_issues:
        description: List of linting issues, if any
        items:
          type: string
        type: array
      results:
        description: The results of each test case executed
        items:
          $ref: '#/definitions/dto.TestCaseResult'
        type: array
      version:
        description: The version of the language used
        type: string
    type: object
  dto.PistonExecuteRequest:
    description: Execute a code with specified parameters.
    properties:
      args:
        items:
          type: string
        type: array
      compile_cpu_time:
        default: 10000
        type: integer
      compile_memory_limit:
        default: -1
        type: integer
      compile_timeout:
        default: 10000
        type: integer
      files:
        items:
          $ref: '#/definitions/dto.File'
        type: array
      language:
        type: string
      run_cpu_time:
        default: 3000
        type: integer
      run_memory_limit:
        default: -1
        type: integer
      run_timeout:
        default: 3000
        type: integer
      stdin:
        type: string
      version:
        type: string
    required:
    - files
    - language
    - version
    type: object
  dto.RuntimeResponse:
    properties:
      aliases:
        items:
          type: string
        type: array
      language:
        type: string
      version:
        type: string
    type: object
  dto.TestCaseResult:
    description: Result of a single test case execution.
    properties:
      actual:
        description: The actual output produced by the program
        type: string
      expected:
        description: The expected output of the program
        type: string
      input:
        description: The input provided to the program
        type: string
      message:
        description: Details about the result or any error
        type: string
      passed:
        description: Whether the output matched the expected output
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/run-and-analyze:
    post:
      consumes:
      - application/json
      description: This endpoint runs and analyzes the input provided in the request
        body.
      parameters:
      - description: Input data for analysis
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ExecuteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully run and analyzed the data
          schema:
            $ref: '#/definitions/dto.MultiExecuteResponse'
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Run and analyze the provided input
      tags:
      - analysis
  /api/v1/runtimes:
    get:
      description: Fetches a list of all available runtimes from the usecase layer.
      produces:
      - application/json
      responses:
        "200":
          description: List of runtimes
          schema:
            items:
              $ref: '#/definitions/dto.RuntimeResponse'
            type: array
        "500":
          description: Failed to fetch runtimes
          schema:
            type: string
      summary: Get all available runtimes
      tags:
      - runtimes
  /health/ping:
    get:
      description: Simple health check to see if the server is running.
      responses:
        "200":
          description: Pong response
          schema:
            type: string
      summary: Ping the server
      tags:
      - health
swagger: "2.0"
